name: Android build
on: pull_request
on: push_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
     - uses: actions/checkout@intialcommit

     - name: Set Up JDK
       uses: actions/setup-java@intialcommit
       with:
        java-version: 1.8
    
     - name: Run Tests
       run: ./gradlew test

     - name: Build Project
       run: ./gradlew assemble
